version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - ./.docker.env
    networks:
      - original-network
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    volumes:
      - postgres:/data/postgres
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '5432:5432'
    env_file:
      - ./.docker.env
    networks:
      - original-network
    restart: unless-stopped

networks:
  original-network:
    driver: bridge

volumes:
  postgres:
    driver: local
